1.What is Numpy?
- Ans: NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. … A powerful N-dimensional array object. Sophisticated (broadcasting) functions.

2. Why NumPy is used in Python?
- Ans: NumPy is a package in Python used for Scientific Computing. NumPy package is used to perform different operations. The ndarray (NumPy Array) is a multidimensional array used to store values of same datatype. These arrays are indexed just like Sequences, starts with zero.

3. How to Install Numpy in Windows? 

- Ans: 
Step 1: Download Python for Windows 10/8/7. First, download the Python executable binaries on your Windows system from the official download the page of the Python. …
Step 2: Run the Python executable installer. …
Step 3: Install pip on Windows 10/8/7. …
Step 4: Install Numpy in Python using pip on Windows 10/8/7.
 
- Installation Process of Numpy..
step1: Open the terminal
step2: type pip install numpy

In [1]:
import numpy as np

4. how to create 1D Array ?

In [4]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [ ]:
num=[1,2,3]
num = np.array(num)
print("1d array : ",num)

5. How to create 2D Array ?

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
num2=[[1,2,3],[4,5,6]]
num2 = np.array(num2)
print("\n2d array : \n",num2)

6. how to create 3D Array or ND Array ?

In [14]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
num3=[[[1,2,3],[4,5,6],[7,8,9]]]
num3 = np.array(num3)
print("\n3d array : \n",num3)

7. how to identified datatyp for numpy array?

In [ ]:
print("\n data type num 3 ", num3.dtype)

In [23]:
(np.array([[1,2,3],[1,2,3]])).dtype

dtype('int32')

8. Print 1D array with 5 zeros.

In [ ]:
arr = np.zeros(5)
print("single array:",arr)

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

9. print zeros with 2 rows and 3 columns ?

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr2 = np.zeros((2,3))
print("Array with 2 rows and 3 cols : \n", arr2)

10. Create array with eye() - diagonal values ?


In [30]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
arr3 = np.eye(4)
print("diaglonal values : \n", arr3)

11. use of diag() square matrix ?

In [34]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
arr3 = np.diag([1,2,3,4])
print("square matrix \n",arr3)

12. Print Range Between 1 To 15 and show 4 integers random numbers

In [35]:
np.random.randint(1,15,4)

array([ 1, 12, 13,  6])

In [ ]:
rand_arr = np.random.randint(1,15,4)
print("\n random number from 1 to 15 ", rand_arr)

13. describe the example of seed() function? and how to use it ? why seed()?

seed() is used in the process of generating the same sequences of random numbers on a constant basis and use the same number at each time when called

In [18]:
np.random.seed(123456789)
random_numbers=np.random.randint(1,20,5)
random_numbers

array([19, 13,  8,  5, 16])

In [14]:
# How many ever times we execute the above code, it will get us the same numbers that are picked randomly for the first time
np.random.seed(123)
rand_arr4 = np.random.randint(1,100,20)
print("seed() showing same number only : ", rand_arr4)

seed() showing same number only :  [67 93 99 18 84 58 87 98 97 48 74 33 47 97 26 84 79 37 97 81]


14. Print first position, last position and 2nd and 3rd position

In [33]:
arr=np.array([5,15,25,35])
print("first position:",arr[0])
print("Second position:",arr[1])
print("Last position:",arr[-1])
print("Third position:",arr[2])

first position: 5
Second position: 15
Last position: 35
Third position: 25


In [41]:
num = np.array([5,15,25,35])
print("first position : ",num[0]) #5
print("third position : ",num[2]) #25

first position :  5
third position :  25


15.  if we don’t know last number of position how to show it by pragmatically?

In [34]:
arr[-1]

35

In [ ]:
num = np.array([5,15,25,35])
print("last indexing done by -1 position : ",num[-1])

16. create a matrix 3 * 3 with value ranging from 0 to 8

In [35]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr = np.arange(0,9).reshape(3,3)
print(arr)


17. create matrix 2 * 2 with value ranging from 1 to 3

In [40]:
np.arange(0,4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [ ]:
arr = np.arange(0,4).reshape(2,2)
print(arr)

18.create matrix 2 * 2 with value ranging from 1 to 4

In [41]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [ ]:
arr = np.arange(1,5).reshape(2,2)
print(arr)

19. print random number from 0 to 1

In [42]:
np.random.rand()

0.06293540361433603

In [ ]:
a = np.random.rand()
print("random number from 0 to 1 ", a)

20.  print size of num array

In [45]:
arr1=np.arange(1,18)
arr1.size

17

In [ ]:
num = np.array([5,15,25,35])
print("\n size \n",num.size) #100

21. create an array of 20 linearly spaced point between 0 to 1


In [46]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
num_line = np.linspace(0,1,20)
print(num_line)

22. Use of sort() function ?

In [56]:
a=np.array([[1,2,3,1,0,-1],[0,9,8,3,-1,45]])
np.sort(a)

array([[-1,  0,  1,  1,  2,  3],
       [-1,  0,  3,  8,  9, 45]])

In [ ]:
num_arr = np.array([[5,6,2],[9,8,1]])
print("sorting of numpy array : \n",np.sort(num_arr))

23. How to get the positions where elements of two arrays match?

In [9]:
arr1=np.array([1,2,3,4,5,6,7,89,9])
arr2=np.array([2,3,4,5,6,1,2,3,9])
np.where(arr1==arr2)

(array([8], dtype=int64),)

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

24. Create a Numpy array filled with all zeros 

In [10]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.zeros(3, dtype = int) 
print("Matrix a : \n", a) 
  
b = np.zeros([3, 3], dtype = int) 
print("\nMatrix b : \n", b) 

25. Check whether a Numpy array contains a specified row

In [47]:
array_2d = np.array([[1,2,3],[4,5,6],[7,2,9],[10,11,12],[13,14,15]])
array_2d
print([1,2,3] in array_2d)
print([45,43,56] in array_2d)

True
False


In [ ]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

# view the array
arr

In [ ]:
## tolist(): used to convert the data elements of an array into a list. 
arr.tolist()

In [ ]:
## checking whether the given list is present in the above array.
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

26. Find the number of occurrences of a sequence in a NumPy array

In [2]:
arr=np.array([[1,2,9,4],[9,4,9,4],[3,4,5,6],[1,9,4,90]])
arr

array([[ 1,  2,  9,  4],
       [ 9,  4,  9,  4],
       [ 3,  4,  5,  6],
       [ 1,  9,  4, 90]])

In [ ]:
seq=list(input("Enter the sequence"))

In [5]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
  

output = repr(arr).count("9, 4")

print(output)

4


27.Write a NumPy program to test element-wise for NaN of a given array.



In [84]:
a = np.array([1, 0, np.nan, np.inf])
np.isnan(a)

array([False, False,  True, False])

28.Write a NumPy program to test whether none of the elements of a given array is zero.




     
     


	


In [89]:
x = np.array([0,1,2,3,0])
np.all(x)

False

29. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.



In [90]:
l = [12.23, 13.32, 100, 36.32]
np.array(l)

array([ 12.23,  13.32, 100.  ,  36.32])

30. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.



In [97]:
x = np.zeros(10)
x[5]=11
print(x)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


31. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.



In [101]:
matrix=np.random.randint(1,100,25).reshape(5,5)
print("5x5 matrix:",matrix)
print("---------")
print("Maximum Value:",matrix.max())
print("Minimum Value:",matrix.min())

5x5 matrix: [[20 99 63 39 46]
 [33 46 18 41 12]
 [36 27 73 62 60]
 [25 25 99 50 51]
 [59 24 65 50 88]]
---------
Maximum Value: 99
Minimum Value: 12


31. Write a NumPy program to compute the multiplication of two given matrixes.
Sample Matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]



In [119]:
mat1 = np.array([[1,0],[0,1]])
mat2 = np.array([[1,2],[3,4]])
print("mat1:",mat1)
print("-----------")
print("mat2:",mat2)
print("------------")
print("Product of two matrices is:", np.dot(mat1,mat2))

mat1: [[1 0]
 [0 1]]
-----------
mat2: [[1 2]
 [3 4]]
------------
Product of two matrices is: [[1 2]
 [3 4]]


33.Create a two-dimensional array with the flattened input as a diagonal

In [123]:
a=np.diagflat([[1,2,3,4],[5,6,7,8]])             # 8x8  matrix
a

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

34. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [126]:
np.trace(a)

36

In [131]:
a = np.arange(24).reshape((2,2,2,3))
print(a)

print("\n")
np.trace(a)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]




array([[18, 20, 22],
       [24, 26, 28]])

In [132]:
a = np.arange(8).reshape((2,2,2))
print(a)
print("\n")
np.trace(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]




array([6, 8])

35. Use of around() function: returns a decimal value rounded to a desired position of the decimal

In [134]:
arr = np.array([12.202, 90.23120, 123.020, 23.202]) 
print("printing the original array values:",end = " ")  
print(arr)  
print("\n")
print("Array values rounded off to 2 decimal position",np.around(arr, 2))  
print("Array values rounded off to -1 decimal position",np.around(arr, -1))  

printing the original array values: [ 12.202   90.2312 123.02    23.202 ]


Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


In [135]:
np.around(arr,-2)

array([  0., 100., 100.,   0.])

In [139]:
np.around(arr,-1)

array([ 10.,  90., 120.,  20.])

In [140]:
np.around(arr,1)

array([ 12.2,  90.2, 123. ,  23.2])

In [141]:
np.around(arr,0)

array([ 12.,  90., 123.,  23.])

In [ ]:
  ##  hundreds,tens,ones<------(.decimalpoint)------->tenths,hundreds,thousands