In [1]:
import numpy as np

In [8]:
a=np.arange(1,20)
arr1=np.array(a)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
arr1[1]

2

In [11]:
arr1[9]

10

In [12]:
arr1[1:11]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
arr1[1:11:2]

array([ 2,  4,  6,  8, 10])

# Broadcasting--->  element wise operation

 Numpy arrays differ from normal python list because of their ability to broadcast:
 

In [14]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [15]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [86]:
# setting a value with index range (Broadcasting)

arr1[:] = 100
arr1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100])

In [21]:
arr2=np.array([1,2,3])
arr3=np.array([4,5,6])

In [26]:
print("addition:",arr2 + arr3) 
print("sub:",arr2 - arr3)
print("product:",arr2 * arr3)
print("division:",arr2 / arr3)

addition: [5 7 9]
sub: [-3 -3 -3]
product: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [32]:
# Create two lists and check any mathematical operation--
#  Why numpy arrays are preffered over python list

l1=[1,2,3]
l2=[4,5,6]
l1-l2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

# Copy()

In [34]:
#  copy operation --

org_array=np.array([1,2,3,4,5])

In [35]:
org_array[3:]=100

In [37]:
print("original array:",org_array)

original array: [  1   2   3 100 100]


In [38]:
#  Assigning the elements of org_array to the new_array

new_array=org_array

In [39]:
new_array

array([  1,   2,   3, 100, 100])

In [40]:
new_array[3:] = 500

In [41]:
new_array

array([  1,   2,   3, 500, 500])

In [43]:
org_array   # see original array  also changed

array([  1,   2,   3, 500, 500])

In [44]:
#  Copy function ---

new1= org_array.copy()

In [47]:
new1[3:]=100

In [49]:
new1

array([  1,   2,   3, 100, 100])

In [50]:
org_array # see using copy function original array remains same----restored backup

array([  1,   2,   3, 500, 500])

# Filtering  Condition ---

In [58]:
arr=np.array([1,2,1010,4,8,18,7])

In [87]:
np.where(arr>100)       # where function outputs index location of condition

(array([2], dtype=int64),)

In [60]:
np.where(arr<100)

(array([0, 1, 3, 4, 5, 6], dtype=int64),)

# Indexing a 2D array(matrices

  The general format is arr_2d[row][col] or arr_2d[row,col].

In [69]:
# arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d=np.array(np.arange(5,50,5).reshape(3,3))

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
#  Getting row
arr_2d[1]

array([20, 25, 30])

In [76]:
# Getting individual element 
# format is arr_2d[row][col]  or arr_2d[row,col]

arr_2d[1][0]

20

In [84]:
# 2d array slicing 
#  Shape (2,2) from top right corner

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
arr_2d[:,1]

array([10, 25, 40])

In [89]:
#  Shape bottom row --

arr_2d[2]

array([35, 40, 45])

# Selection --

 Let's briefly go over how to use brackets for selection based off comparison operators.

In [93]:
arr= np.arange(1,11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])